package org.anwb.hv.alcincident;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-24T14:29:27.883+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "AlcIncidentService", 
                  wsdlLocation = "file:AlcIncident.wsdl",
                  targetNamespace = "http://anwb.org/hv/alcincident") 
public class AlcIncidentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://anwb.org/hv/alcincident", "AlcIncidentService");
    public final static QName AlcIncidentPort = new QName("http://anwb.org/hv/alcincident", "AlcIncidentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:AlcIncident.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlcIncidentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:AlcIncident.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlcIncidentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlcIncidentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlcIncidentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlcIncidentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AlcIncidentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AlcIncidentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AlcIncident
     */
    @WebEndpoint(name = "AlcIncidentPort")
    public AlcIncident getAlcIncidentPort() {
        return super.getPort(AlcIncidentPort, AlcIncident.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlcIncident
     */
    @WebEndpoint(name = "AlcIncidentPort")
    public AlcIncident getAlcIncidentPort(WebServiceFeature... features) {
        return super.getPort(AlcIncidentPort, AlcIncident.class, features);
    }

}
