package org.anwb.hv.alcincident;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-24T14:29:27.856+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://anwb.org/hv/alcincident", name = "AlcIncident")
@XmlSeeAlso({org.anwb.hv.ict.oxi.obi.ObjectFactory.class, org.anwb.hv.ict.oxi.callinc.ObjectFactory.class})
@SOAPBinding(use = SOAPBinding.Use.ENCODED, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AlcIncident {

    @WebMethod(action = "eindemeldenIncident")
    @Oneway
    public void eindemeldenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.callinc.EindemeldenIncidentMessage message
    );

    @WebMethod(action = "completerenIncident")
    @Oneway
    public void completerenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.callinc.CompleterenIncidentMessage message
    );

    @WebMethod(action = "meldenStatus")
    @Oneway
    public void meldenStatus(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.callinc.MeldenStatusMessage message
    );

    @WebMethod(action = "teruggevenIncident")
    @Oneway
    public void teruggevenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.callinc.TeruggevenIncidentMessage message
    );
}
