package org.anwb.hv.disincident;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-24T14:29:32.460+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "DisIncidentService", 
                  wsdlLocation = "file:DisIncident.wsdl",
                  targetNamespace = "http://anwb.org/hv/disincident") 
public class DisIncidentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://anwb.org/hv/disincident", "DisIncidentService");
    public final static QName DisIncidentPort = new QName("http://anwb.org/hv/disincident", "DisIncidentPort");
    static {
        URL url = null;
        try {
            url = new URL("file:DisIncident.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DisIncidentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:DisIncident.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DisIncidentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DisIncidentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DisIncidentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DisIncidentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DisIncidentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DisIncidentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DisIncident
     */
    @WebEndpoint(name = "DisIncidentPort")
    public DisIncident getDisIncidentPort() {
        return super.getPort(DisIncidentPort, DisIncident.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisIncident
     */
    @WebEndpoint(name = "DisIncidentPort")
    public DisIncident getDisIncidentPort(WebServiceFeature... features) {
        return super.getPort(DisIncidentPort, DisIncident.class, features);
    }

}
