package org.anwb.hv.disincident;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-24T14:29:32.433+01:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://anwb.org/hv/disincident", name = "DisIncident")
@XmlSeeAlso({org.anwb.hv.ict.oxi.disinc.ObjectFactory.class, org.anwb.hv.ict.oxi.obi.ObjectFactory.class})
@SOAPBinding(use = SOAPBinding.Use.ENCODED, parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DisIncident {

    @WebMethod(action = "opvragenPlanningsInfo")
    @WebResult(name = "message", targetNamespace = "", partName = "message")
    public org.anwb.hv.ict.oxi.disinc.AntwoordenPlanningsinfoMessage opvragenPlanningsInfo(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.disinc.OpvragenPlanningsinfoMessage message
    );

    @WebMethod(action = "opvragenOpdrachtInfo")
    @WebResult(name = "message", targetNamespace = "", partName = "message")
    public org.anwb.hv.ict.oxi.disinc.AntwoordenOpdrachtinfoMessage opvragenOpdrachtInfo(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.disinc.OpvragenOpdrachtinfoMessage message
    );

    @WebMethod(action = "wijzigenIncident")
    @Oneway
    public void wijzigenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.disinc.WijzigenIncidentMessage message
    );

    @WebMethod(action = "afmeldenIncident")
    @Oneway
    public void afmeldenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.disinc.AfmeldenIncidentMessage message
    );

    @WebMethod(action = "aanmeldenIncident")
    @Oneway
    public void aanmeldenIncident(
        @WebParam(partName = "message", name = "message", targetNamespace = "")
        org.anwb.hv.ict.oxi.disinc.AanmeldenIncidentMessage message
    );
}
